name: hrushikesh_portfolio
description: A new Flutter project.

publish_to: I personal portfolio with detail's about my work and profile

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rive: ^0.11.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/rive/
    - assets/images/portfolio/